"""baseline schema

Squashed baseline generated from the SQLAlchemy models (Base.metadata), which are
the source of truth for the schema (the app runs create_all on startup). This
replaces the drifted 001-024 chain that could not run end-to-end on an empty DB.
Existing databases are re-stamped to this revision by docker-entrypoint.sh; only
genuinely fresh databases execute it.

Revision ID: 001
Revises:
Create Date: 2026-06-15

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "001"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admins",
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("added_by", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_table(
        "api_keys",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("key_prefix", sa.String(length=12), nullable=False),
        sa.Column(
            "scopes",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_api_keys_key_hash"), "api_keys", ["key_hash"], unique=True)
    op.create_table(
        "chatops_commands",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("repo", sa.String(length=256), nullable=False),
        sa.Column("pr_id", sa.String(length=64), nullable=False),
        sa.Column("command", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_detail", sa.Text(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=True),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform", "external_id", "command", name="uq_chatops_command_external"
        ),
    )
    op.create_index(
        op.f("ix_chatops_commands_platform"), "chatops_commands", ["platform"], unique=False
    )
    op.create_index(op.f("ix_chatops_commands_pr_id"), "chatops_commands", ["pr_id"], unique=False)
    op.create_index(op.f("ix_chatops_commands_repo"), "chatops_commands", ["repo"], unique=False)
    op.create_table(
        "connections",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.String(length=256), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("auth_kind", sa.String(length=32), nullable=True),
        sa.Column("org_url", sa.Text(), nullable=True),
        sa.Column("encrypted_token", sa.Text(), nullable=True),
        sa.Column("token_secret_ref", sa.Text(), nullable=True),
        sa.Column("token_prefix", sa.String(length=20), nullable=False),
        sa.Column("app_id", sa.String(length=64), nullable=True),
        sa.Column("app_slug", sa.String(length=128), nullable=True),
        sa.Column("installation_id", sa.String(length=64), nullable=True),
        sa.Column("installation_account", sa.String(length=256), nullable=True),
        sa.Column("installation_target_type", sa.String(length=32), nullable=True),
        sa.Column("encrypted_private_key", sa.Text(), nullable=True),
        sa.Column("private_key_fingerprint", sa.String(length=128), nullable=True),
        sa.Column(
            "app_permissions",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("health_status", sa.String(length=16), nullable=False),
        sa.Column("health_message", sa.Text(), nullable=False),
        sa.Column("health_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sync_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("updated_by", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "health_status in ('unknown', 'healthy', 'unhealthy')",
            name="ck_connections_health_status",
        ),
        sa.CheckConstraint("platform in ('github', 'ado')", name="ck_connections_platform"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_connections_name"), "connections", ["name"], unique=True)
    op.create_index(op.f("ix_connections_platform"), "connections", ["platform"], unique=False)
    op.create_index(
        "uq_connections_single_default_github",
        "connections",
        ["is_default"],
        unique=True,
        postgresql_where=sa.text(
            "platform = 'github' AND is_default = TRUE AND archived_at IS NULL"
        ),
        sqlite_where=sa.text("platform = 'github' AND is_default = 1 AND archived_at IS NULL"),
    )
    op.create_table(
        "excluded_repos",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("org", sa.String(length=256), nullable=False),
        sa.Column("project", sa.String(length=256), nullable=False),
        sa.Column("repo", sa.String(length=256), nullable=False),
        sa.Column("excluded_by_email", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "org", "project", "repo", name="uq_excluded_repo"),
    )
    op.create_table(
        "exclusion_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("org_pattern", sa.String(length=256), nullable=False),
        sa.Column("project_pattern", sa.String(length=256), nullable=False),
        sa.Column("repo_pattern", sa.String(length=256), nullable=False),
        sa.Column("created_by_email", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "finding_dismissals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pr_id", sa.String(length=64), nullable=False),
        sa.Column("repo", sa.String(length=256), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("signature", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column(
            "source_finding",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolution_kind", sa.String(length=24), nullable=True),
        sa.Column("fixed_by_sha", sa.String(length=64), nullable=True),
        sa.Column("fixed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verified_by", sa.String(length=256), nullable=True),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("regressed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("regressed_from_sha", sa.String(length=64), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_finding_dismissals_pr_id"), "finding_dismissals", ["pr_id"], unique=False
    )
    op.create_index(
        op.f("ix_finding_dismissals_signature"), "finding_dismissals", ["signature"], unique=False
    )
    op.create_table(
        "global_config",
        sa.Column("key", sa.String(length=128), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "guidance_comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("repo", sa.String(length=256), nullable=False),
        sa.Column("pr_id", sa.String(length=64), nullable=False),
        sa.Column("comment_id", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "repo", "pr_id", name="uq_guidance_comment_pr"),
    )
    op.create_index(
        op.f("ix_guidance_comments_platform"), "guidance_comments", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_guidance_comments_pr_id"), "guidance_comments", ["pr_id"], unique=False
    )
    op.create_index(op.f("ix_guidance_comments_repo"), "guidance_comments", ["repo"], unique=False)
    op.create_table(
        "profile_audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column(
            "before",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "after",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "profile_managers",
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("added_by", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "settings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("updated_by", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_profiles_name"), "profiles", ["name"], unique=True)
    op.create_table(
        "prompt_overrides",
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("agent_name"),
    )
    op.create_table(
        "user_identities",
        sa.Column("email", sa.String(length=256), nullable=False),
        sa.Column("github_handle", sa.String(length=128), nullable=True),
        sa.Column("ado_upn", sa.String(length=256), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("email"),
    )
    op.create_table(
        "repo_links",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("org_url", sa.Text(), nullable=False),
        sa.Column("project", sa.String(length=256), nullable=False),
        sa.Column("repo_owner", sa.String(length=256), nullable=False),
        sa.Column("repo_name", sa.String(length=256), nullable=False),
        sa.Column("repo_url", sa.Text(), nullable=False),
        sa.Column("canonical_repo_key", sa.String(length=512), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=False),
        sa.Column("auto_review_enabled", sa.Boolean(), nullable=False),
        sa.Column("paused", sa.Boolean(), nullable=False),
        sa.Column(
            "require_review_check", sa.Boolean(), server_default=sa.text("true"), nullable=False
        ),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.String(length=256), nullable=False),
        sa.Column("updated_by", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_repo_links_canonical_repo_key"),
        "repo_links",
        ["canonical_repo_key"],
        unique=False,
    )
    op.create_index(op.f("ix_repo_links_platform"), "repo_links", ["platform"], unique=False)
    op.create_index(
        "uq_repo_links_active_canonical",
        "repo_links",
        ["platform", "canonical_repo_key"],
        unique=True,
        postgresql_where=sa.text("archived_at IS NULL"),
        sqlite_where=sa.text("archived_at IS NULL"),
    )
    op.create_table(
        "sync_sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("org", sa.String(length=256), nullable=False),
        sa.Column("project", sa.String(length=256), nullable=False),
        sa.Column("repo", sa.String(length=256), nullable=False),
        sa.Column("repo_url", sa.Text(), nullable=False),
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column(
            "connection_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("last_synced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sync_sources_platform"), "sync_sources", ["platform"], unique=False)
    op.create_table(
        "readiness_candidates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("repo_link_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("org_url", sa.Text(), nullable=False),
        sa.Column("project", sa.String(length=256), nullable=False),
        sa.Column("repo_owner", sa.String(length=256), nullable=False),
        sa.Column("repo_name", sa.String(length=256), nullable=False),
        sa.Column("repo", sa.String(length=512), nullable=False),
        sa.Column("canonical_repo_key", sa.String(length=512), nullable=False),
        sa.Column("pr_id", sa.String(length=64), nullable=False),
        sa.Column("pr_url", sa.Text(), nullable=False),
        sa.Column("head_sha", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column(
            "readiness_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "profile_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column(
            "connection_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state in ('waiting', 'blocked', 'reviewing', 'reviewed', 'superseded', 'error')",
            name="ck_readiness_candidates_state",
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repo_link_id"],
            ["repo_links.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "platform",
            "canonical_repo_key",
            "pr_id",
            "head_sha",
            name="uq_readiness_candidate_sha",
        ),
    )
    op.create_index(
        op.f("ix_readiness_candidates_canonical_repo_key"),
        "readiness_candidates",
        ["canonical_repo_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_readiness_candidates_head_sha"),
        "readiness_candidates",
        ["head_sha"],
        unique=False,
    )
    op.create_index(
        op.f("ix_readiness_candidates_platform"),
        "readiness_candidates",
        ["platform"],
        unique=False,
    )
    op.create_index(
        op.f("ix_readiness_candidates_pr_id"), "readiness_candidates", ["pr_id"], unique=False
    )
    op.create_index(
        op.f("ix_readiness_candidates_repo"), "readiness_candidates", ["repo"], unique=False
    )
    op.create_index(
        op.f("ix_readiness_candidates_repo_link_id"),
        "readiness_candidates",
        ["repo_link_id"],
        unique=False,
    )
    op.create_table(
        "scans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scan_type", sa.String(length=32), nullable=False),
        sa.Column("repo", sa.String(length=256), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("time_window_days", sa.Integer(), nullable=False),
        sa.Column("staleness_months", sa.Integer(), nullable=False),
        sa.Column("total_findings", sa.Integer(), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("stage_detail", sa.Text(), nullable=False),
        sa.Column(
            "pipeline_log",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("total_input_tokens", sa.Integer(), nullable=False),
        sa.Column("total_output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column(
            "profile_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column(
            "connection_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("repo_link_id", sa.UUID(), nullable=True),
        sa.Column("scan_source", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repo_link_id"],
            ["repo_links.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scans_repo"), "scans", ["repo"], unique=False)
    op.create_index(op.f("ix_scans_scan_type"), "scans", ["scan_type"], unique=False)
    op.create_table(
        "synced_prs",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("pr_id", sa.String(length=64), nullable=False),
        sa.Column("org", sa.String(length=256), nullable=False),
        sa.Column("project", sa.String(length=256), nullable=False),
        sa.Column("repo", sa.String(length=256), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=256), nullable=False),
        sa.Column("author_display", sa.String(length=256), nullable=False),
        sa.Column("pr_url", sa.Text(), nullable=False),
        sa.Column("source_branch", sa.String(length=256), nullable=False),
        sa.Column("target_branch", sa.String(length=256), nullable=False),
        sa.Column("is_draft", sa.Boolean(), nullable=False),
        sa.Column("has_conflicts", sa.Boolean(), nullable=False),
        sa.Column("approval_status", sa.String(length=32), nullable=False),
        sa.Column(
            "reviewers",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "assignees",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("ci_status", sa.String(length=32), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column(
            "profile_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column(
            "connection_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("repo_link_id", sa.UUID(), nullable=True),
        sa.Column("sync_source", sa.String(length=32), nullable=False),
        sa.Column("pr_created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("pr_updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("synced_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repo_link_id"],
            ["repo_links.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("platform", "pr_id", "repo", "project", name="uq_synced_pr"),
    )
    op.create_index(op.f("ix_synced_prs_author"), "synced_prs", ["author"], unique=False)
    op.create_index(op.f("ix_synced_prs_org"), "synced_prs", ["org"], unique=False)
    op.create_index(op.f("ix_synced_prs_platform"), "synced_prs", ["platform"], unique=False)
    op.create_index(op.f("ix_synced_prs_repo"), "synced_prs", ["repo"], unique=False)
    op.create_table(
        "readiness_candidate_transitions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("from_state", sa.String(length=16), nullable=True),
        sa.Column("to_state", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("actor", sa.String(length=256), nullable=False),
        sa.Column("reason", sa.String(length=128), nullable=False),
        sa.Column(
            "readiness_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "from_state is null or from_state in ('waiting', 'blocked', 'reviewing', 'reviewed', 'superseded', 'error')",
            name="ck_readiness_transitions_from_state",
        ),
        sa.CheckConstraint(
            "to_state in ('waiting', 'blocked', 'reviewing', 'reviewed', 'superseded', 'error')",
            name="ck_readiness_transitions_to_state",
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["readiness_candidates.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_readiness_candidate_transitions_candidate_id"),
        "readiness_candidate_transitions",
        ["candidate_id"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("pr_id", sa.String(length=64), nullable=False),
        sa.Column("repo", sa.String(length=256), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("author", sa.String(length=128), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source_branch", sa.String(length=256), nullable=False),
        sa.Column("target_branch", sa.String(length=256), nullable=False),
        sa.Column("head_commit_sha", sa.String(length=64), nullable=False),
        sa.Column("pr_url", sa.Text(), nullable=False),
        sa.Column("risk_tier", sa.String(length=16), nullable=False),
        sa.Column("repo_risk_class", sa.String(length=16), nullable=False),
        sa.Column("trust_tier", sa.String(length=32), nullable=False),
        sa.Column(
            "trust_tier_details",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("combined_score", sa.Float(), nullable=False),
        sa.Column("decision", sa.String(length=32), nullable=False),
        sa.Column("mechanical_passed", sa.Boolean(), nullable=False),
        sa.Column(
            "override_reasons",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("stage", sa.String(length=32), nullable=False),
        sa.Column("stage_detail", sa.Text(), nullable=False),
        sa.Column(
            "pipeline_log",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("total_input_tokens", sa.Integer(), nullable=False),
        sa.Column("total_output_tokens", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=False),
        sa.Column("comment_mode", sa.String(length=32), server_default="none", nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=True),
        sa.Column(
            "profile_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("connection_id", sa.UUID(), nullable=True),
        sa.Column(
            "connection_snapshot",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("repo_link_id", sa.UUID(), nullable=True),
        sa.Column("candidate_id", sa.UUID(), nullable=True),
        sa.Column("review_source", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column(
            "postback_meta",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id"],
            ["readiness_candidates.id"],
        ),
        sa.ForeignKeyConstraint(
            ["connection_id"],
            ["connections.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["repo_link_id"],
            ["repo_links.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_pr_id"), "reviews", ["pr_id"], unique=False)
    op.create_index(op.f("ix_reviews_repo"), "reviews", ["repo"], unique=False)
    op.create_table(
        "scan_agent_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column("summary", sa.Text(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scan_agent_results_agent_name"),
        "scan_agent_results",
        ["agent_name"],
        unique=False,
    )
    op.create_table(
        "scan_issues",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("scan_id", sa.UUID(), nullable=False),
        sa.Column(
            "finding_ids",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("issue_url", sa.Text(), nullable=False),
        sa.Column("issue_number", sa.String(length=32), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("repo", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["scan_id"], ["scans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_scan_issues_scan_id"), "scan_issues", ["scan_id"], unique=False)
    op.create_table(
        "agent_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("agent_name", sa.String(length=64), nullable=False),
        sa.Column("verdict", sa.String(length=16), nullable=False),
        sa.Column(
            "languages_reviewed",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("verdict_explanation", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_agent_results_agent_name"), "agent_results", ["agent_name"], unique=False
    )
    op.create_table(
        "mechanical_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("tool", sa.String(length=64), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column(
            "findings",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["review_id"], ["reviews.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "posted_inline_comments",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("review_id", sa.UUID(), nullable=False),
        sa.Column("platform_comment_id", sa.String(length=256), nullable=False),
        sa.Column("platform", sa.String(length=16), nullable=False),
        sa.Column("pr_id", sa.String(length=64), nullable=False),
        sa.Column("repo", sa.String(length=256), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["review_id"],
            ["reviews.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_posted_inline_comments_review_id"),
        "posted_inline_comments",
        ["review_id"],
        unique=False,
    )
    op.create_table(
        "scan_findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_result_id", sa.UUID(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("certainty", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("file", sa.Text(), nullable=False),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("suggestion", sa.Text(), nullable=False),
        sa.Column("priority", sa.Float(), nullable=False),
        sa.Column("last_modified", sa.String(length=64), nullable=True),
        sa.Column("effort_estimate", sa.String(length=16), nullable=True),
        sa.ForeignKeyConstraint(
            ["agent_result_id"], ["scan_agent_results.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "findings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("agent_result_id", sa.UUID(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("certainty", sa.String(length=16), nullable=False),
        sa.Column("category", sa.String(length=128), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("file", sa.Text(), nullable=False),
        sa.Column("line", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("suggestion", sa.Text(), nullable=False),
        sa.Column("cwe", sa.String(length=32), nullable=True),
        sa.ForeignKeyConstraint(["agent_result_id"], ["agent_results.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###

    # Bootstrap admin (preserved from the squashed migration 008). created_at is
    # supplied explicitly because the model default is Python-side, not a DB default.
    op.execute(
        "INSERT INTO admins (email, added_by, created_at) "
        "VALUES ('ewi@projectum.com', 'system', now()) "
        "ON CONFLICT (email) DO NOTHING"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("findings")
    op.drop_table("scan_findings")
    op.drop_index(op.f("ix_posted_inline_comments_review_id"), table_name="posted_inline_comments")
    op.drop_table("posted_inline_comments")
    op.drop_table("mechanical_results")
    op.drop_index(op.f("ix_agent_results_agent_name"), table_name="agent_results")
    op.drop_table("agent_results")
    op.drop_index(op.f("ix_scan_issues_scan_id"), table_name="scan_issues")
    op.drop_table("scan_issues")
    op.drop_index(op.f("ix_scan_agent_results_agent_name"), table_name="scan_agent_results")
    op.drop_table("scan_agent_results")
    op.drop_index(op.f("ix_reviews_repo"), table_name="reviews")
    op.drop_index(op.f("ix_reviews_pr_id"), table_name="reviews")
    op.drop_table("reviews")
    op.drop_index(
        op.f("ix_readiness_candidate_transitions_candidate_id"),
        table_name="readiness_candidate_transitions",
    )
    op.drop_table("readiness_candidate_transitions")
    op.drop_index(op.f("ix_synced_prs_repo"), table_name="synced_prs")
    op.drop_index(op.f("ix_synced_prs_platform"), table_name="synced_prs")
    op.drop_index(op.f("ix_synced_prs_org"), table_name="synced_prs")
    op.drop_index(op.f("ix_synced_prs_author"), table_name="synced_prs")
    op.drop_table("synced_prs")
    op.drop_index(op.f("ix_scans_scan_type"), table_name="scans")
    op.drop_index(op.f("ix_scans_repo"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(op.f("ix_readiness_candidates_repo_link_id"), table_name="readiness_candidates")
    op.drop_index(op.f("ix_readiness_candidates_repo"), table_name="readiness_candidates")
    op.drop_index(op.f("ix_readiness_candidates_pr_id"), table_name="readiness_candidates")
    op.drop_index(op.f("ix_readiness_candidates_platform"), table_name="readiness_candidates")
    op.drop_index(op.f("ix_readiness_candidates_head_sha"), table_name="readiness_candidates")
    op.drop_index(
        op.f("ix_readiness_candidates_canonical_repo_key"), table_name="readiness_candidates"
    )
    op.drop_table("readiness_candidates")
    op.drop_index(op.f("ix_sync_sources_platform"), table_name="sync_sources")
    op.drop_table("sync_sources")
    op.drop_index(
        "uq_repo_links_active_canonical",
        table_name="repo_links",
        postgresql_where=sa.text("archived_at IS NULL"),
        sqlite_where=sa.text("archived_at IS NULL"),
    )
    op.drop_index(op.f("ix_repo_links_platform"), table_name="repo_links")
    op.drop_index(op.f("ix_repo_links_canonical_repo_key"), table_name="repo_links")
    op.drop_table("repo_links")
    op.drop_table("user_identities")
    op.drop_table("prompt_overrides")
    op.drop_index(op.f("ix_profiles_name"), table_name="profiles")
    op.drop_table("profiles")
    op.drop_table("profile_managers")
    op.drop_table("profile_audit_events")
    op.drop_index(op.f("ix_guidance_comments_repo"), table_name="guidance_comments")
    op.drop_index(op.f("ix_guidance_comments_pr_id"), table_name="guidance_comments")
    op.drop_index(op.f("ix_guidance_comments_platform"), table_name="guidance_comments")
    op.drop_table("guidance_comments")
    op.drop_table("global_config")
    op.drop_index(op.f("ix_finding_dismissals_signature"), table_name="finding_dismissals")
    op.drop_index(op.f("ix_finding_dismissals_pr_id"), table_name="finding_dismissals")
    op.drop_table("finding_dismissals")
    op.drop_table("exclusion_rules")
    op.drop_table("excluded_repos")
    op.drop_index(
        "uq_connections_single_default_github",
        table_name="connections",
        postgresql_where=sa.text(
            "platform = 'github' AND is_default = TRUE AND archived_at IS NULL"
        ),
        sqlite_where=sa.text("platform = 'github' AND is_default = 1 AND archived_at IS NULL"),
    )
    op.drop_index(op.f("ix_connections_platform"), table_name="connections")
    op.drop_index(op.f("ix_connections_name"), table_name="connections")
    op.drop_table("connections")
    op.drop_index(op.f("ix_chatops_commands_repo"), table_name="chatops_commands")
    op.drop_index(op.f("ix_chatops_commands_pr_id"), table_name="chatops_commands")
    op.drop_index(op.f("ix_chatops_commands_platform"), table_name="chatops_commands")
    op.drop_table("chatops_commands")
    op.drop_index(op.f("ix_api_keys_key_hash"), table_name="api_keys")
    op.drop_table("api_keys")
    op.drop_table("admins")
    # ### end Alembic commands ###
